//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ClusterSwitchPolicy) DeepCopyInto(out *ClusterSwitchPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of ClusterSwitchPolicy.
func (in *ClusterSwitchPolicy) DeepCopy() *ClusterSwitchPolicy {
	if in == nil {
		return nil
	}
	out := new(ClusterSwitchPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *ClusterSwitchPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of ClusterSwitchPolicyList.
func (in *ClusterSwitchPolicyList) DeepCopyInto(out *ClusterSwitchPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterSwitchPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of ClusterSwitchPolicyList.
func (in *ClusterSwitchPolicyList) DeepCopy() *ClusterSwitchPolicyList {
	if in == nil {
		return nil
	}
	out := new(ClusterSwitchPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *ClusterSwitchPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies ClusterSwitchPolicySpec.
func (in *ClusterSwitchPolicySpec) DeepCopyInto(out *ClusterSwitchPolicySpec) {
	*out = *in
	out.LocalMySQL = in.LocalMySQL
	out.RemoteMySQL = in.RemoteMySQL
	if in.ProxySQL != nil {
		in, out := &in.ProxySQL, &out.ProxySQL
		*out = make([]ProxySQLEndpoint, len(*in))
		copy(*out, *in)
	}
	out.HealthCheck = in.HealthCheck
	out.Switchover = in.Switchover
}

// DeepCopy creates a deep copy of ClusterSwitchPolicySpec.
func (in *ClusterSwitchPolicySpec) DeepCopy() *ClusterSwitchPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ClusterSwitchPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies ClusterSwitchPolicyStatus.
func (in *ClusterSwitchPolicyStatus) DeepCopyInto(out *ClusterSwitchPolicyStatus) {
	*out = *in
	in.LocalHealth.DeepCopyInto(&out.LocalHealth)
	in.RemoteHealth.DeepCopyInto(&out.RemoteHealth)
	if in.LastSwitchoverTime != nil {
		in, out := &in.LastSwitchoverTime, &out.LastSwitchoverTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of ClusterSwitchPolicyStatus.
func (in *ClusterSwitchPolicyStatus) DeepCopy() *ClusterSwitchPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterSwitchPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies ClusterHealthStatus.
func (in *ClusterHealthStatus) DeepCopyInto(out *ClusterHealthStatus) {
	*out = *in
	if in.LastChecked != nil {
		in, out := &in.LastChecked, &out.LastChecked
		*out = (*in).DeepCopy()
	}
}

// DeepCopy creates a deep copy of ClusterHealthStatus.
func (in *ClusterHealthStatus) DeepCopy() *ClusterHealthStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterHealthStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies MySQLEndpointConfig.
func (in *MySQLEndpointConfig) DeepCopyInto(out *MySQLEndpointConfig) {
	*out = *in
}

// DeepCopy creates a deep copy of MySQLEndpointConfig.
func (in *MySQLEndpointConfig) DeepCopy() *MySQLEndpointConfig {
	if in == nil {
		return nil
	}
	out := new(MySQLEndpointConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies ProxySQLEndpoint.
func (in *ProxySQLEndpoint) DeepCopyInto(out *ProxySQLEndpoint) {
	*out = *in
}

// DeepCopy creates a deep copy of ProxySQLEndpoint.
func (in *ProxySQLEndpoint) DeepCopy() *ProxySQLEndpoint {
	if in == nil {
		return nil
	}
	out := new(ProxySQLEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies SecretRef.
func (in *SecretRef) DeepCopyInto(out *SecretRef) {
	*out = *in
}

// DeepCopy creates a deep copy of SecretRef.
func (in *SecretRef) DeepCopy() *SecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies HealthCheckConfig.
func (in *HealthCheckConfig) DeepCopyInto(out *HealthCheckConfig) {
	*out = *in
}

// DeepCopy creates a deep copy of HealthCheckConfig.
func (in *HealthCheckConfig) DeepCopy() *HealthCheckConfig {
	if in == nil {
		return nil
	}
	out := new(HealthCheckConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies SwitchoverConfig.
func (in *SwitchoverConfig) DeepCopyInto(out *SwitchoverConfig) {
	*out = *in
}

// DeepCopy creates a deep copy of SwitchoverConfig.
func (in *SwitchoverConfig) DeepCopy() *SwitchoverConfig {
	if in == nil {
		return nil
	}
	out := new(SwitchoverConfig)
	in.DeepCopyInto(out)
	return out
}
