//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ClusterSwitchPolicy) DeepCopyInto(out *ClusterSwitchPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of ClusterSwitchPolicy.
func (in *ClusterSwitchPolicy) DeepCopy() *ClusterSwitchPolicy {
	if in == nil {
		return nil
	}
	out := new(ClusterSwitchPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *ClusterSwitchPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of ClusterSwitchPolicyList.
func (in *ClusterSwitchPolicyList) DeepCopyInto(out *ClusterSwitchPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterSwitchPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of ClusterSwitchPolicyList.
func (in *ClusterSwitchPolicyList) DeepCopy() *ClusterSwitchPolicyList {
	if in == nil {
		return nil
	}
	out := new(ClusterSwitchPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *ClusterSwitchPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies ClusterSwitchPolicySpec.
func (in *ClusterSwitchPolicySpec) DeepCopyInto(out *ClusterSwitchPolicySpec) {
	*out = *in
	out.LocalMySQL = in.LocalMySQL
	out.RemoteMySQL = in.RemoteMySQL
	if in.ProxySQL != nil {
		inS, outS := &in.ProxySQL, &out.ProxySQL
		*outS = make([]ProxySQLEndpoint, len(*inS))
		copy(*outS, *inS)
	}
	out.HealthCheck = in.HealthCheck
	out.Switchover = in.Switchover
	out.PreFlight = in.PreFlight
	if in.MANO != nil {
		inM, outM := &in.MANO, &out.MANO
		*outM = new(MANOConfig)
		(*inM).DeepCopyInto(*outM)
	}
	if in.RemoteKubeAPI != nil {
		inR, outR := &in.RemoteKubeAPI, &out.RemoteKubeAPI
		*outR = new(RemoteKubeAPIConfig)
		(*inR).DeepCopyInto(*outR)
	}
}

// DeepCopy creates a deep copy of ClusterSwitchPolicySpec.
func (in *ClusterSwitchPolicySpec) DeepCopy() *ClusterSwitchPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ClusterSwitchPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies ClusterSwitchPolicyStatus.
func (in *ClusterSwitchPolicyStatus) DeepCopyInto(out *ClusterSwitchPolicyStatus) {
	*out = *in
	in.LocalHealth.DeepCopyInto(&out.LocalHealth)
	in.RemoteHealth.DeepCopyInto(&out.RemoteHealth)
	if in.LastSwitchoverTime != nil {
		in2, out2 := &in.LastSwitchoverTime, &out.LastSwitchoverTime
		*out2 = (*in2).DeepCopy()
	}
	if in.SwitchoverProgress != nil {
		out.SwitchoverProgress = in.SwitchoverProgress.DeepCopy()
	}
	if in.LastPreFlight != nil {
		out.LastPreFlight = in.LastPreFlight.DeepCopy()
	}
	if in.Conditions != nil {
		inC, outC := &in.Conditions, &out.Conditions
		*outC = make([]metav1.Condition, len(*inC))
		for i := range *inC {
			(*inC)[i].DeepCopyInto(&(*outC)[i])
		}
	}
}

// DeepCopy creates a deep copy of ClusterSwitchPolicyStatus.
func (in *ClusterSwitchPolicyStatus) DeepCopy() *ClusterSwitchPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterSwitchPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies ClusterHealthStatus.
func (in *ClusterHealthStatus) DeepCopyInto(out *ClusterHealthStatus) {
	*out = *in
	if in.LastChecked != nil {
		in2, out2 := &in.LastChecked, &out.LastChecked
		*out2 = (*in2).DeepCopy()
	}
}

// DeepCopy creates a deep copy of ClusterHealthStatus.
func (in *ClusterHealthStatus) DeepCopy() *ClusterHealthStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterHealthStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies MySQLEndpointConfig.
func (in *MySQLEndpointConfig) DeepCopyInto(out *MySQLEndpointConfig) {
	*out = *in
}

// DeepCopy creates a deep copy of MySQLEndpointConfig.
func (in *MySQLEndpointConfig) DeepCopy() *MySQLEndpointConfig {
	if in == nil {
		return nil
	}
	out := new(MySQLEndpointConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies ProxySQLEndpoint.
func (in *ProxySQLEndpoint) DeepCopyInto(out *ProxySQLEndpoint) {
	*out = *in
}

// DeepCopy creates a deep copy of ProxySQLEndpoint.
func (in *ProxySQLEndpoint) DeepCopy() *ProxySQLEndpoint {
	if in == nil {
		return nil
	}
	out := new(ProxySQLEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies SecretRef.
func (in *SecretRef) DeepCopyInto(out *SecretRef) {
	*out = *in
}

// DeepCopy creates a deep copy of SecretRef.
func (in *SecretRef) DeepCopy() *SecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies HealthCheckConfig.
func (in *HealthCheckConfig) DeepCopyInto(out *HealthCheckConfig) {
	*out = *in
}

// DeepCopy creates a deep copy of HealthCheckConfig.
func (in *HealthCheckConfig) DeepCopy() *HealthCheckConfig {
	if in == nil {
		return nil
	}
	out := new(HealthCheckConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies SwitchoverConfig.
func (in *SwitchoverConfig) DeepCopyInto(out *SwitchoverConfig) {
	*out = *in
}

// DeepCopy creates a deep copy of SwitchoverConfig.
func (in *SwitchoverConfig) DeepCopy() *SwitchoverConfig {
	if in == nil {
		return nil
	}
	out := new(SwitchoverConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies PreFlightConfig.
func (in *PreFlightConfig) DeepCopyInto(out *PreFlightConfig) {
	*out = *in
}

// DeepCopy creates a deep copy of PreFlightConfig.
func (in *PreFlightConfig) DeepCopy() *PreFlightConfig {
	if in == nil {
		return nil
	}
	out := new(PreFlightConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies MANOConfig.
func (in *MANOConfig) DeepCopyInto(out *MANOConfig) {
	*out = *in
	if in.TokenSecretRef != nil {
		out.TokenSecretRef = in.TokenSecretRef.DeepCopy()
	}
	if in.CredentialsSecretRef != nil {
		out.CredentialsSecretRef = in.CredentialsSecretRef.DeepCopy()
	}
}

// DeepCopy creates a deep copy of MANOConfig.
func (in *MANOConfig) DeepCopy() *MANOConfig {
	if in == nil {
		return nil
	}
	out := new(MANOConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies RemoteKubeAPIConfig.
func (in *RemoteKubeAPIConfig) DeepCopyInto(out *RemoteKubeAPIConfig) {
	*out = *in
	if in.CASecretRef != nil {
		out.CASecretRef = in.CASecretRef.DeepCopy()
	}
	out.TokenSecretRef = in.TokenSecretRef
}

// DeepCopy creates a deep copy of RemoteKubeAPIConfig.
func (in *RemoteKubeAPIConfig) DeepCopy() *RemoteKubeAPIConfig {
	if in == nil {
		return nil
	}
	out := new(RemoteKubeAPIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies SwitchoverProgress.
func (in *SwitchoverProgress) DeepCopyInto(out *SwitchoverProgress) {
	*out = *in
	out.StartedAt = *in.StartedAt.DeepCopy()
	if in.CompletedPhases != nil {
		inP, outP := &in.CompletedPhases, &out.CompletedPhases
		*outP = make([]string, len(*inP))
		copy(*outP, *inP)
	}
}

// DeepCopy creates a deep copy of SwitchoverProgress.
func (in *SwitchoverProgress) DeepCopy() *SwitchoverProgress {
	if in == nil {
		return nil
	}
	out := new(SwitchoverProgress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies PreFlightStatus.
func (in *PreFlightStatus) DeepCopyInto(out *PreFlightStatus) {
	*out = *in
	out.PassedAt = *in.PassedAt.DeepCopy()
	if in.Checks != nil {
		inC, outC := &in.Checks, &out.Checks
		*outC = make([]PreFlightCheck, len(*inC))
		copy(*outC, *inC)
	}
}

// DeepCopy creates a deep copy of PreFlightStatus.
func (in *PreFlightStatus) DeepCopy() *PreFlightStatus {
	if in == nil {
		return nil
	}
	out := new(PreFlightStatus)
	in.DeepCopyInto(out)
	return out
}
