//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoSkipConfig) DeepCopyInto(out *AutoSkipConfig) {
	*out = *in
	if in.ErrorCodeWhitelist != nil {
		in, out := &in.ErrorCodeWhitelist, &out.ErrorCodeWhitelist
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
	out.Window = in.Window
	out.QuarantineWindow = in.QuarantineWindow
	out.HistoryRetention = in.HistoryRetention
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoSkipConfig.
func (in *AutoSkipConfig) DeepCopy() *AutoSkipConfig {
	if in == nil {
		return nil
	}
	out := new(AutoSkipConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterHealthStatus) DeepCopyInto(out *ClusterHealthStatus) {
	*out = *in
	if in.LastChecked != nil {
		in, out := &in.LastChecked, &out.LastChecked
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterHealthStatus.
func (in *ClusterHealthStatus) DeepCopy() *ClusterHealthStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterHealthStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSwitchPolicy) DeepCopyInto(out *ClusterSwitchPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSwitchPolicy.
func (in *ClusterSwitchPolicy) DeepCopy() *ClusterSwitchPolicy {
	if in == nil {
		return nil
	}
	out := new(ClusterSwitchPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterSwitchPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSwitchPolicyList) DeepCopyInto(out *ClusterSwitchPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterSwitchPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSwitchPolicyList.
func (in *ClusterSwitchPolicyList) DeepCopy() *ClusterSwitchPolicyList {
	if in == nil {
		return nil
	}
	out := new(ClusterSwitchPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterSwitchPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSwitchPolicySpec) DeepCopyInto(out *ClusterSwitchPolicySpec) {
	*out = *in
	out.LocalMySQL = in.LocalMySQL
	out.RemoteMySQL = in.RemoteMySQL
	if in.ProxySQL != nil {
		in, out := &in.ProxySQL, &out.ProxySQL
		*out = make([]ProxySQLEndpoint, len(*in))
		copy(*out, *in)
	}
	if in.ProxySQLSelector != nil {
		in, out := &in.ProxySQLSelector, &out.ProxySQLSelector
		*out = new(ProxySQLSelectorConfig)
		(*in).DeepCopyInto(*out)
	}
	out.HealthCheck = in.HealthCheck
	out.Switchover = in.Switchover
	out.PreFlight = in.PreFlight
	if in.MANO != nil {
		in, out := &in.MANO, &out.MANO
		*out = new(MANOConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.RemoteKubeAPI != nil {
		in, out := &in.RemoteKubeAPI, &out.RemoteKubeAPI
		*out = new(RemoteKubeAPIConfig)
		(*in).DeepCopyInto(*out)
	}
	out.Recovery = in.Recovery
	if in.ReplicationErrorHandling != nil {
		in, out := &in.ReplicationErrorHandling, &out.ReplicationErrorHandling
		*out = new(ReplicationErrorHandlingConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSwitchPolicySpec.
func (in *ClusterSwitchPolicySpec) DeepCopy() *ClusterSwitchPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ClusterSwitchPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSwitchPolicyStatus) DeepCopyInto(out *ClusterSwitchPolicyStatus) {
	*out = *in
	in.LocalHealth.DeepCopyInto(&out.LocalHealth)
	in.RemoteHealth.DeepCopyInto(&out.RemoteHealth)
	if in.LastSwitchoverTime != nil {
		in, out := &in.LastSwitchoverTime, &out.LastSwitchoverTime
		*out = (*in).DeepCopy()
	}
	if in.LastDegradedRecoveryAttempt != nil {
		in, out := &in.LastDegradedRecoveryAttempt, &out.LastDegradedRecoveryAttempt
		*out = (*in).DeepCopy()
	}
	if in.SwitchoverProgress != nil {
		in, out := &in.SwitchoverProgress, &out.SwitchoverProgress
		*out = new(SwitchoverProgress)
		(*in).DeepCopyInto(*out)
	}
	if in.LastPreFlight != nil {
		in, out := &in.LastPreFlight, &out.LastPreFlight
		*out = new(PreFlightStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GTIDLag != nil {
		in, out := &in.GTIDLag, &out.GTIDLag
		*out = new(GTIDLagStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ReplicationErrors != nil {
		in, out := &in.ReplicationErrors, &out.ReplicationErrors
		*out = new(ReplicationErrorStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSwitchPolicyStatus.
func (in *ClusterSwitchPolicyStatus) DeepCopy() *ClusterSwitchPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterSwitchPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GTIDLagStatus) DeepCopyInto(out *GTIDLagStatus) {
	*out = *in
	in.MeasuredAt.DeepCopyInto(&out.MeasuredAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GTIDLagStatus.
func (in *GTIDLagStatus) DeepCopy() *GTIDLagStatus {
	if in == nil {
		return nil
	}
	out := new(GTIDLagStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckConfig) DeepCopyInto(out *HealthCheckConfig) {
	*out = *in
	out.Interval = in.Interval
	out.MySQLCheckTimeout = in.MySQLCheckTimeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckConfig.
func (in *HealthCheckConfig) DeepCopy() *HealthCheckConfig {
	if in == nil {
		return nil
	}
	out := new(HealthCheckConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MANOConfig) DeepCopyInto(out *MANOConfig) {
	*out = *in
	if in.TokenSecretRef != nil {
		in, out := &in.TokenSecretRef, &out.TokenSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	out.PollInterval = in.PollInterval
	out.PollTimeout = in.PollTimeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MANOConfig.
func (in *MANOConfig) DeepCopy() *MANOConfig {
	if in == nil {
		return nil
	}
	out := new(MANOConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLEndpointConfig) DeepCopyInto(out *MySQLEndpointConfig) {
	*out = *in
	out.CredentialsSecretRef = in.CredentialsSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLEndpointConfig.
func (in *MySQLEndpointConfig) DeepCopy() *MySQLEndpointConfig {
	if in == nil {
		return nil
	}
	out := new(MySQLEndpointConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreFlightCheck) DeepCopyInto(out *PreFlightCheck) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreFlightCheck.
func (in *PreFlightCheck) DeepCopy() *PreFlightCheck {
	if in == nil {
		return nil
	}
	out := new(PreFlightCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreFlightConfig) DeepCopyInto(out *PreFlightConfig) {
	*out = *in
	out.CatchupTimeout = in.CatchupTimeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreFlightConfig.
func (in *PreFlightConfig) DeepCopy() *PreFlightConfig {
	if in == nil {
		return nil
	}
	out := new(PreFlightConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreFlightStatus) DeepCopyInto(out *PreFlightStatus) {
	*out = *in
	in.PassedAt.DeepCopyInto(&out.PassedAt)
	if in.Checks != nil {
		in, out := &in.Checks, &out.Checks
		*out = make([]PreFlightCheck, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreFlightStatus.
func (in *PreFlightStatus) DeepCopy() *PreFlightStatus {
	if in == nil {
		return nil
	}
	out := new(PreFlightStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxySQLEndpoint) DeepCopyInto(out *ProxySQLEndpoint) {
	*out = *in
	out.CredentialsSecretRef = in.CredentialsSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxySQLEndpoint.
func (in *ProxySQLEndpoint) DeepCopy() *ProxySQLEndpoint {
	if in == nil {
		return nil
	}
	out := new(ProxySQLEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxySQLSelectorConfig) DeepCopyInto(out *ProxySQLSelectorConfig) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.CredentialsSecretRef = in.CredentialsSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxySQLSelectorConfig.
func (in *ProxySQLSelectorConfig) DeepCopy() *ProxySQLSelectorConfig {
	if in == nil {
		return nil
	}
	out := new(ProxySQLSelectorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryConfig) DeepCopyInto(out *RecoveryConfig) {
	*out = *in
	out.AutoRecoveryInterval = in.AutoRecoveryInterval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryConfig.
func (in *RecoveryConfig) DeepCopy() *RecoveryConfig {
	if in == nil {
		return nil
	}
	out := new(RecoveryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteKubeAPIConfig) DeepCopyInto(out *RemoteKubeAPIConfig) {
	*out = *in
	if in.CASecretRef != nil {
		in, out := &in.CASecretRef, &out.CASecretRef
		*out = new(SecretRef)
		**out = **in
	}
	out.TokenSecretRef = in.TokenSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteKubeAPIConfig.
func (in *RemoteKubeAPIConfig) DeepCopy() *RemoteKubeAPIConfig {
	if in == nil {
		return nil
	}
	out := new(RemoteKubeAPIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationErrorEntry) DeepCopyInto(out *ReplicationErrorEntry) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationErrorEntry.
func (in *ReplicationErrorEntry) DeepCopy() *ReplicationErrorEntry {
	if in == nil {
		return nil
	}
	out := new(ReplicationErrorEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationErrorHandlingConfig) DeepCopyInto(out *ReplicationErrorHandlingConfig) {
	*out = *in
	in.AutoSkip.DeepCopyInto(&out.AutoSkip)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationErrorHandlingConfig.
func (in *ReplicationErrorHandlingConfig) DeepCopy() *ReplicationErrorHandlingConfig {
	if in == nil {
		return nil
	}
	out := new(ReplicationErrorHandlingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationErrorStatus) DeepCopyInto(out *ReplicationErrorStatus) {
	*out = *in
	if in.LastError != nil {
		in, out := &in.LastError, &out.LastError
		*out = new(ReplicationErrorEntry)
		(*in).DeepCopyInto(*out)
	}
	if in.SkippedTransactions != nil {
		in, out := &in.SkippedTransactions, &out.SkippedTransactions
		*out = make([]SkippedTransaction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.QuarantinedSince != nil {
		in, out := &in.QuarantinedSince, &out.QuarantinedSince
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationErrorStatus.
func (in *ReplicationErrorStatus) DeepCopy() *ReplicationErrorStatus {
	if in == nil {
		return nil
	}
	out := new(ReplicationErrorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRef) DeepCopyInto(out *SecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRef.
func (in *SecretRef) DeepCopy() *SecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkippedTransaction) DeepCopyInto(out *SkippedTransaction) {
	*out = *in
	in.SkippedAt.DeepCopyInto(&out.SkippedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkippedTransaction.
func (in *SkippedTransaction) DeepCopy() *SkippedTransaction {
	if in == nil {
		return nil
	}
	out := new(SkippedTransaction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwitchoverConfig) DeepCopyInto(out *SwitchoverConfig) {
	*out = *in
	out.Timeout = in.Timeout
	out.DrainTimeout = in.DrainTimeout
	out.FenceTimeout = in.FenceTimeout
	out.CooldownPeriod = in.CooldownPeriod
	out.ResumeStuckTimeout = in.ResumeStuckTimeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwitchoverConfig.
func (in *SwitchoverConfig) DeepCopy() *SwitchoverConfig {
	if in == nil {
		return nil
	}
	out := new(SwitchoverConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwitchoverProgress) DeepCopyInto(out *SwitchoverProgress) {
	*out = *in
	in.StartedAt.DeepCopyInto(&out.StartedAt)
	if in.CompletedPhases != nil {
		in, out := &in.CompletedPhases, &out.CompletedPhases
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwitchoverProgress.
func (in *SwitchoverProgress) DeepCopy() *SwitchoverProgress {
	if in == nil {
		return nil
	}
	out := new(SwitchoverProgress)
	in.DeepCopyInto(out)
	return out
}
